spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/initialsgame
    username: initialsgame
    password: initialsgame
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
